# å…¨ä½“ã®ãƒ¬ã‚¤ã‚¢ã‚¦ãƒˆæ§‹æˆ
add_newline = true

format = """
[î‚¶](bg:none fg:#3B4252)\
$os\
[ | ](bg:#3B4252 fg:#666666)\
$username\
[ | ](bg:#3B4252 fg:#666666)\
$directory\
[î‚°](fg:#3B4252 bg:none)\
$git_branch\
$git_status\
$line_break\
$character"""

right_format = """
[î‚²](fg:#3B4252 bg:none)\
$battery\
[ | ](bg:#3B4252 fg:#666666)\
$time\
[î‚´](fg:#3B4252 bg:none)"""

[os]
disabled = false
style = "bg:#3B4252 fg:#D8DEE9"
symbols.Macos = "ï…¹"

[username]
show_always = true
style_user = "bg:#3B4252 fg:#D8DEE9"
format = "[$user]($style)"

[directory]
style = "bg:#3B4252 fg:#88C0D0"
home_symbol = "~"
truncation_length = 6
truncate_to_repo = false
fish_style_pwd_dir_length = 1
format = "[ó°‰‹ $path]($style)"

[git_branch]
symbol = "ï˜ "
style = "bg:#A3BE8C fg:#2E3440"
format = "[[](fg:none bg:#A3BE8C) on ó°Š¤ $symbol$branch]($style)"

[git_status]
style = "bg:#A3BE8C fg:#2E3440"
format = "[$all_status$ahead_behind]($style)[î‚°](fg:#A3BE8C bg:none)"
modified = "!$count"
untracked = "?$count"

[battery]
full_symbol = "ğŸ”‹ "
format = "[$percentage$symbol](bg:#3B4252 fg:#A3BE8C)"

[[battery.display]]
threshold = 100
style = "bg:#3B4252 fg:#A3BE8C"

[time]
disabled = false
time_format = "%H:%M:%S"
style = "bg:#3B4252 fg:#D8DEE9"
format = "[at $time ğŸ•’ ]($style)"

[character]
success_symbol = "[â¯](bold green) "
error_symbol = "[â¯](bold red) "
